import { Container, CssBaseline } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import RootLayout from "@/components/layout/RootLayout";
import light from "@/theme/light";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={light}>
          <CssBaseline />
          {/* <CToaster /> */}
          {/* <TopHeader /> */}
          {/* <BottomHeader /> */}
          <RootLayout>
            {children}
          </RootLayout>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
