"""implement lesson progress module

Revision ID: 10070958ec7a
Revises: 20da38631744
Create Date: 2026-04-11 00:06:49.935724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10070958ec7a'
down_revision: Union[str, Sequence[str], None] = '20da38631744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('current_time', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_user_lesson_progress')
    )
    op.create_index('idx_progress_lesson', 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index('idx_progress_updated_at', 'lesson_progress', ['updated_at'], unique=False)
    op.create_index('idx_progress_user', 'lesson_progress', ['user_id'], unique=False)
    op.create_index('idx_progress_user_updated', 'lesson_progress', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_lesson_progress_is_completed'), 'lesson_progress', ['is_completed'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_is_completed'), table_name='lesson_progress')
    op.drop_index('idx_progress_user_updated', table_name='lesson_progress')
    op.drop_index('idx_progress_user', table_name='lesson_progress')
    op.drop_index('idx_progress_updated_at', table_name='lesson_progress')
    op.drop_index('idx_progress_lesson', table_name='lesson_progress')
    op.drop_table('lesson_progress')
    # ### end Alembic commands ###
