"""update_category_and_course_badges

Revision ID: 3f1bf7ed9cc1
Revises: c3ae2517e7b0
Create Date: 2026-06-06 13:36:01.001720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f1bf7ed9cc1'
down_revision: Union[str, Sequence[str], None] = 'c3ae2517e7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type first
    course_badge_enum = postgresql.ENUM('none', 'featured', name='course_badge_enum')
    course_badge_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('categories', sa.Column('badge', sa.String(length=20), server_default='none', nullable=False))
    op.drop_index(op.f('ix_categories_banner'), table_name='categories')
    op.drop_index(op.f('ix_categories_type'), table_name='categories')
    op.create_index(op.f('ix_categories_badge'), 'categories', ['badge'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.drop_column('categories', 'banner')
    op.drop_column('categories', 'type')
    op.add_column('courses', sa.Column('badge', sa.Enum('none', 'featured', name='course_badge_enum'), server_default='none', nullable=False))
    op.drop_index(op.f('idx_courses_status_active_created'), table_name='courses')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.create_index('idx_courses_badge_active_created', 'courses', ['badge', 'is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_courses_badge'), 'courses', ['badge'], unique=False)
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', postgresql.ENUM('draft', 'published', 'archived', name='course_status_enum'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_courses_badge'), table_name='courses')
    op.drop_index('idx_courses_badge_active_created', table_name='courses')
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.create_index(op.f('idx_courses_status_active_created'), 'courses', ['status', 'is_active', 'created_at'], unique=False)
    op.drop_column('courses', 'badge')
    
    # Drop course_badge_enum type
    course_badge_enum = postgresql.ENUM('none', 'featured', name='course_badge_enum')
    course_badge_enum.drop(op.get_bind(), checkfirst=True)

    op.add_column('categories', sa.Column('type', sa.VARCHAR(length=20), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('banner', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_badge'), table_name='categories')
    op.create_index(op.f('ix_categories_type'), 'categories', ['type'], unique=False)
    op.create_index(op.f('ix_categories_banner'), 'categories', ['banner'], unique=False)
    op.drop_column('categories', 'badge')
    # ### end Alembic commands ###
