"""add discussion and comment tables

Revision ID: 4b98ae60207c
Revises: 10070958ec7a
Create Date: 2026-04-11 00:21:47.601440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b98ae60207c'
down_revision: Union[str, Sequence[str], None] = '10070958ec7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_discussion_course', 'discussions', ['course_id'], unique=False)
    op.create_index('idx_discussion_lesson', 'discussions', ['lesson_id'], unique=False)
    op.create_index('idx_discussion_user', 'discussions', ['user_id'], unique=False)
    op.create_index(op.f('ix_discussions_course_id'), 'discussions', ['course_id'], unique=False)
    op.create_index(op.f('ix_discussions_is_active'), 'discussions', ['is_active'], unique=False)
    op.create_index(op.f('ix_discussions_lesson_id'), 'discussions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_discussions_user_id'), 'discussions', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_discussion', 'comments', ['discussion_id'], unique=False)
    op.create_index('idx_comment_user', 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_discussion_id'), 'comments', ['discussion_id'], unique=False)
    op.create_index(op.f('ix_comments_is_active'), 'comments', ['is_active'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_active'), table_name='comments')
    op.drop_index(op.f('ix_comments_discussion_id'), table_name='comments')
    op.drop_index('idx_comment_user', table_name='comments')
    op.drop_index('idx_comment_discussion', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_discussions_user_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_lesson_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_is_active'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_course_id'), table_name='discussions')
    op.drop_index('idx_discussion_user', table_name='discussions')
    op.drop_index('idx_discussion_lesson', table_name='discussions')
    op.drop_index('idx_discussion_course', table_name='discussions')
    op.drop_table('discussions')
    # ### end Alembic commands ###
