"""implement_question_module

Revision ID: 4f7bb33c5caa
Revises: 61656f9bd5e3
Create Date: 2026-04-11 09:30:17.476653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7bb33c5caa'
down_revision: Union[str, Sequence[str], None] = '61656f9bd5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    question_type_enum = postgresql.ENUM('MCQ_SINGLE', 'MCQ_MULTIPLE', 'TRUE_FALSE', 'SHORT_ANSWER', name='question_type_enum')
    question_type_enum.create(op.get_bind())

    op.add_column('choices', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.Enum('MCQ_SINGLE', 'MCQ_MULTIPLE', 'TRUE_FALSE', 'SHORT_ANSWER', name='question_type_enum'), nullable=False))
    op.add_column('questions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index('idx_question_category', 'questions', ['category_id'], unique=False)
    op.create_index('idx_question_course', 'questions', ['course_id'], unique=False)
    op.create_index('idx_question_quiz', 'questions', ['quiz_id'], unique=False)
    op.create_index('idx_question_type', 'questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_questions_category_id'), 'questions', ['category_id'], unique=False)
    op.create_index(op.f('ix_questions_course_id'), 'questions', ['course_id'], unique=False)
    op.create_index(op.f('ix_questions_created_by_id'), 'questions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_column('questions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('type', postgresql.ENUM('MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER', name='questiontype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_by_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_course_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_category_id'), table_name='questions')
    op.drop_index('idx_question_type', table_name='questions')
    op.drop_index('idx_question_quiz', table_name='questions')
    op.drop_index('idx_question_course', table_name='questions')
    op.drop_index('idx_question_category', table_name='questions')
    op.alter_column('questions', 'points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('questions', 'is_active')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'created_by_id')
    op.drop_column('questions', 'category_id')
    op.drop_column('questions', 'course_id')
    op.drop_column('choices', 'explanation')
    # ### end Alembic commands ###
