"""Add category thumbnail

Revision ID: 854a832958bf
Revises: 8f0d4a08c654
Create Date: 2026-04-13 02:33:28.187782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854a832958bf'
down_revision: Union[str, Sequence[str], None] = '8f0d4a08c654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'thumbnail')
    # ### end Alembic commands ###
