"""add category type

Revision ID: 8f0d4a08c654
Revises: 780e16b3a4c1
Create Date: 2026-04-13 02:13:00.750071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0d4a08c654'
down_revision: Union[str, Sequence[str], None] = '780e16b3a4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', sa.String(length=20), nullable=False, server_default='normal'))
    op.create_index(op.f('ix_categories_type'), 'categories', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_type'), table_name='categories')
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###
