"""rename video_url to video in lessons

Revision ID: 906fb1505325
Revises: f1dd666d2312
Create Date: 2026-06-01 04:23:02.795170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906fb1505325'
down_revision: Union[str, Sequence[str], None] = 'f1dd666d2312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video', sa.Text(), nullable=True))
    op.drop_column('lessons', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('lessons', 'video')
    # ### end Alembic commands ###
