"""move avatar to base user

Revision ID: 9c8f1b452199
Revises: 3f1bf7ed9cc1
Create Date: 2026-06-07 02:13:18.313934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8f1b452199'
down_revision: Union[str, Sequence[str], None] = '3f1bf7ed9cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.execute("UPDATE users SET avatar = students.avatar FROM students WHERE users.id = students.id")
    op.execute("UPDATE users SET avatar = instructors.avatar FROM instructors WHERE users.id = instructors.id")
    op.drop_column('instructors', 'avatar')
    op.drop_column('students', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('instructors', sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.execute("UPDATE students SET avatar = users.avatar FROM users WHERE students.id = users.id")
    op.execute("UPDATE instructors SET avatar = users.avatar FROM users WHERE instructors.id = users.id")
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
