"""add_ai_content_models

Revision ID: bf96e17e4bb8
Revises: bf93661e85ff
Create Date: 2026-08-01 03:38:12.489764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf96e17e4bb8'
down_revision: Union[str, Sequence[str], None] = 'bf93661e85ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_source_contents',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_source_contents_created_at'), 'ai_source_contents', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_source_contents_owner_id'), 'ai_source_contents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ai_source_contents_public_id'), 'ai_source_contents', ['public_id'], unique=True)
    op.create_table('ai_draft_quizzes',
    sa.Column('source_content_id', sa.BigInteger(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('quiz_data', sa.JSON(), nullable=False),
    sa.Column('quality_report', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confirmed_quiz_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_quiz_id'], ['quizzes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_content_id'], ['ai_source_contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_draft_quizzes_confirmed_quiz_id'), 'ai_draft_quizzes', ['confirmed_quiz_id'], unique=False)
    op.create_index(op.f('ix_ai_draft_quizzes_created_at'), 'ai_draft_quizzes', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_draft_quizzes_owner_id'), 'ai_draft_quizzes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ai_draft_quizzes_public_id'), 'ai_draft_quizzes', ['public_id'], unique=True)
    op.create_index(op.f('ix_ai_draft_quizzes_source_content_id'), 'ai_draft_quizzes', ['source_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_draft_quizzes_source_content_id'), table_name='ai_draft_quizzes')
    op.drop_index(op.f('ix_ai_draft_quizzes_public_id'), table_name='ai_draft_quizzes')
    op.drop_index(op.f('ix_ai_draft_quizzes_owner_id'), table_name='ai_draft_quizzes')
    op.drop_index(op.f('ix_ai_draft_quizzes_created_at'), table_name='ai_draft_quizzes')
    op.drop_index(op.f('ix_ai_draft_quizzes_confirmed_quiz_id'), table_name='ai_draft_quizzes')
    op.drop_table('ai_draft_quizzes')
    op.drop_index(op.f('ix_ai_source_contents_public_id'), table_name='ai_source_contents')
    op.drop_index(op.f('ix_ai_source_contents_owner_id'), table_name='ai_source_contents')
    op.drop_index(op.f('ix_ai_source_contents_created_at'), table_name='ai_source_contents')
    op.drop_table('ai_source_contents')
    # ### end Alembic commands ###
