"""Add category banner

Revision ID: c2ea6012ad25
Revises: cff03c200860
Create Date: 2026-05-05 00:24:37.888155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ea6012ad25'
down_revision: Union[str, Sequence[str], None] = 'cff03c200860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('banner', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_categories_banner'), 'categories', ['banner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_banner'), table_name='categories')
    op.drop_column('categories', 'banner')
    # ### end Alembic commands ###
