"""add module_id to quiz

Revision ID: c3ae2517e7b0
Revises: 906fb1505325
Create Date: 2026-06-03 01:04:27.607251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ae2517e7b0'
down_revision: Union[str, Sequence[str], None] = '906fb1505325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('module_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quizzes_module_id'), 'quizzes', ['module_id'], unique=False)
    op.create_foreign_key(None, 'quizzes', 'modules', ['module_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_index(op.f('ix_quizzes_module_id'), table_name='quizzes')
    op.drop_column('quizzes', 'module_id')
    # ### end Alembic commands ###
