"""add joined table inheritance for students and instructors

Revision ID: c970ce9dec62
Revises: 675670b6dba5
Create Date: 2026-03-30 07:26:41.420614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c970ce9dec62'
down_revision: Union[str, Sequence[str], None] = '675670b6dba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=False),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # Add type as nullable first to avoid NOT NULL violation on existing data
    op.add_column('users', sa.Column('type', sa.String(length=20), nullable=True))
    # Set default value for existing users based on their role
    op.execute("UPDATE users SET type = 'user' WHERE type IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'type', existing_type=sa.String(length=20), nullable=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'type')
    op.drop_table('students')
    op.drop_table('instructors')
    # ### end Alembic commands ###
