"""Add media table

Revision ID: cff03c200860
Revises: 854a832958bf
Create Date: 2026-05-05 00:24:09.514446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cff03c200860'
down_revision: Union[str, Sequence[str], None] = '854a832958bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('CLOUDINARY', 'S3', 'IMAGEKIT', 'LOCAL', name='media_provider_enum'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(model IS NULL AND model_id IS NULL) OR (model IS NOT NULL AND model_id IS NOT NULL)', name='ck_media_model_pair'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_model_model_id', 'media', ['model', 'model_id'], unique=False)
    op.create_index('idx_media_provider', 'media', ['provider'], unique=False)
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_is_used'), 'media', ['is_used'], unique=False)
    op.alter_column('categories', 'thumbnail',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_thumbnail'), 'categories', ['thumbnail'], unique=False)
    op.create_index(op.f('ix_choices_created_at'), 'choices', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_courses_created_at'), 'courses', ['created_at'], unique=False)
    op.create_index(op.f('ix_discussions_created_at'), 'discussions', ['created_at'], unique=False)
    op.create_index(op.f('ix_enrollments_created_at'), 'enrollments', ['created_at'], unique=False)
    op.create_index(op.f('ix_lesson_progress_created_at'), 'lesson_progress', ['created_at'], unique=False)
    op.create_index(op.f('ix_modules_created_at'), 'modules', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_answers_created_at'), 'quiz_attempt_answers', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_created_at'), 'quiz_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_quizzes_created_at'), 'quizzes', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_quizzes_created_at'), table_name='quizzes')
    op.drop_index(op.f('ix_quiz_attempts_created_at'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempt_answers_created_at'), table_name='quiz_attempt_answers')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_index(op.f('ix_modules_created_at'), table_name='modules')
    op.drop_index(op.f('ix_lesson_progress_created_at'), table_name='lesson_progress')
    op.drop_index(op.f('ix_enrollments_created_at'), table_name='enrollments')
    op.drop_index(op.f('ix_discussions_created_at'), table_name='discussions')
    op.drop_index(op.f('ix_courses_created_at'), table_name='courses')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_choices_created_at'), table_name='choices')
    op.drop_index(op.f('ix_categories_thumbnail'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.alter_column('categories', 'thumbnail',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_media_is_used'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_index('idx_media_provider', table_name='media')
    op.drop_index('idx_media_model_model_id', table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
