"""add_status_fields_to_ai_source_content

Revision ID: dfe9be404285
Revises: bf96e17e4bb8
Create Date: 2026-08-02 19:50:05.343270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfe9be404285"
down_revision: Union[str, Sequence[str], None] = "bf96e17e4bb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_source_contents",
        sa.Column(
            "status", sa.String(length=50), nullable=False, server_default="completed"
        ),
    )
    op.add_column(
        "ai_source_contents", sa.Column("error_message", sa.Text(), nullable=True)
    )
    op.add_column(
        "ai_source_contents",
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_source_contents", "celery_task_id")
    op.drop_column("ai_source_contents", "error_message")
    op.drop_column("ai_source_contents", "status")
    # ### end Alembic commands ###
