"""rename profile_picture_url to avatar in users

Revision ID: f1dd666d2312
Revises: a7756d2fec58
Create Date: 2026-05-27 00:43:15.503050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1dd666d2312'
down_revision: Union[str, Sequence[str], None] = 'a7756d2fec58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.drop_column('instructors', 'profile_picture_url')
    op.add_column('students', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.drop_column('students', 'profile_picture_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'avatar')
    op.add_column('instructors', sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('instructors', 'avatar')
    # ### end Alembic commands ###
