import { ROUTES } from "@/lib/constants/routes"
import {
  SpaceDashboardOutlined,
  CategoryOutlined,
  PeopleAltOutlined,
  MenuBookOutlined,
  QuizOutlined,
  CoPresentOutlined,
  AssignmentTurnedInOutlined,
  AccountTreeOutlined,
  GroupsOutlined,
  LiveTvOutlined,
  LibraryBooksOutlined,
  AssignmentOutlined,
  GradingOutlined,
  WorkspacePremiumOutlined,
  MilitaryTechOutlined,
  FavoriteBorderOutlined,
  ReceiptLongOutlined,
  LocalOfferOutlined,
  ConfirmationNumberOutlined,
  SettingsOutlined,
  MailOutline,
  DescriptionOutlined,
  PaymentsOutlined,
  SchoolOutlined,
  PersonOutline,
  PendingActionsOutlined,
  StarsOutlined,
  HowToRegOutlined,
  PeopleOutline,
} from "@mui/icons-material"

export const settingsMenuItems = [
  {
    group: "Settings",
    title: "Profile",
    path: "/settings/profile",
    icon: <PersonOutline />,
  },
  {
    group: "Settings",
    title: "General",
    path: "/settings/general",
    icon: <SettingsOutlined />,
    resource: "setting",
    action: "read",
  },
  {
    group: "Settings",
    title: "Users",
    path: "/settings/users",
    icon: <PeopleAltOutlined />,
    resource: "user",
    action: "read",
  },
  {
    group: "Settings",
    title: "Email Accounts",
    path: "/settings/email-accounts",
    icon: <MailOutline />,
    resource: "email_account",
    action: "read",
  },
  {
    group: "Settings",
    title: "Email Templates",
    path: "/settings/email-templates",
    icon: <DescriptionOutlined />,
    resource: "email_template",
    action: "read",
  },
  {
    group: "Payments",
    title: "Payment Gateways",
    path: "/settings/payment-gateways",
    icon: <PaymentsOutlined />,
    resource: "setting",
    action: "read",
  },
  {
    group: "Payments",
    title: "Transactions",
    path: "/settings/transactions",
    icon: <ReceiptLongOutlined />,
    resource: "payment",
    action: "read",
  },
  {
    group: "Payments",
    title: "Coupons",
    path: "/settings/coupons",
    icon: <LocalOfferOutlined />,
    resource: "coupon",
    action: "read",
  },
]

export const lmsMenuItems = [
  {
    group: "Overview",
    title: ROUTES.admin.dashboard.label,
    path: ROUTES.admin.dashboard.path,
    icon: <SpaceDashboardOutlined />,
    resource: "dashboard",
    action: "read",
  },
  {
    group: "E-Learning",
    title: ROUTES.admin.category.label,
    path: ROUTES.admin.category.path,
    icon: <CategoryOutlined />,
    resource: "category",
    action: "read",
  },
  {
    group: "E-Learning",
    title: ROUTES.admin.course.label,
    path: ROUTES.admin.course.path,
    icon: <SchoolOutlined />,
    resource: "course",
    action: "read",
  },
  {
    group: "E-Learning",
    title: ROUTES.admin.quiz.label,
    path: ROUTES.admin.quiz.path,
    icon: <QuizOutlined />,
    resource: "quiz",
    action: "read",
  },
  {
    group: "E-Learning",
    title: ROUTES.admin.ebook.label,
    path: ROUTES.admin.ebook.path,
    icon: <LibraryBooksOutlined />,
    resource: "ebook",
    action: "read",
  },
  {
    group: "Programs & Batches",
    title: ROUTES.admin.program.label,
    path: ROUTES.admin.program.path,
    icon: <AccountTreeOutlined />,
    resource: "program",
    action: "read",
  },
  {
    group: "Programs & Batches",
    title: ROUTES.admin.batch.label,
    path: ROUTES.admin.batch.path,
    icon: <GroupsOutlined />,
    resource: "batch",
    action: "read",
  },
  {
    group: "Programs & Batches",
    title: ROUTES.admin.liveClass.label,
    path: ROUTES.admin.liveClass.path,
    icon: <LiveTvOutlined />,
    resource: "live_class",
    action: "read",
  },
  {
    group: "Assessments",
    title: ROUTES.admin.assignment.label,
    path: ROUTES.admin.assignment.path,
    icon: <AssignmentOutlined />,
    resource: "assignment",
    action: "read",
  },
  {
    group: "Assessments",
    title: ROUTES.admin.certificateRequest.label,
    path: ROUTES.admin.certificateRequest.path,
    icon: <PendingActionsOutlined />,
    resource: "evaluation",
    action: "read",
  },
  {
    group: "Assessments",
    title: ROUTES.admin.evaluation.label,
    path: ROUTES.admin.evaluation.path,
    icon: <GradingOutlined />,
    resource: "evaluation",
    action: "read",
  },
  {
    group: "Assessments",
    title: ROUTES.admin.certificate.label,
    path: ROUTES.admin.certificate.path,
    icon: <WorkspacePremiumOutlined />,
    resource: "certificate",
    action: "read",
  },
  {
    group: "Assessments",
    title: ROUTES.admin.badge.label,
    path: ROUTES.admin.badge.path,
    icon: <MilitaryTechOutlined />,
    resource: "lms_badge",
    action: "read",
  },
  {
    group: "Assessments",
    title: "Badge Assignments",
    path: "/lms/badges/assignments",
    icon: <StarsOutlined />,
    resource: "badge_assignment",
    action: "read",
  },
  {
    group: "Management",
    title: ROUTES.admin.enrollment.label,
    path: ROUTES.admin.enrollment.path,
    icon: <HowToRegOutlined />,
    resource: "enrollment",
    action: "read",
  },
]

export const academyMenuItems = [
  {
    title: "Dashboard",
    path: "/academy/dashboard",
    icon: <SpaceDashboardOutlined />,
  },
  {
    title: "Courses",
    path: "/academy/courses",
    icon: <SchoolOutlined />,
  },
  {
    title: "Batches",
    path: "/academy/batches",
    icon: <GroupsOutlined />,
    resource: "batch",
    action: "read",
  },
  {
    title: "Programs",
    path: "/academy/programs",
    icon: <AccountTreeOutlined />,
    resource: "program",
    action: "read",
  },
  {
    title: "My Badges",
    path: "/academy/badges",
    icon: <MilitaryTechOutlined />,
    resource: "badge",
    action: "read",
  },
  {
    title: "Profile",
    path: "/academy/profile",
    icon: <PersonOutline />,
  },
]

export const coreMenuItems = [
  {
    title: "Users",
    path: "/core/users",
    icon: <PeopleOutline />,
    resource: "user",
    action: "read",
  },
]
