"""add expanded user fields and email verification

Revision ID: c536f5d85d75
Revises: c970ce9dec62
Create Date: 2026-03-30 07:51:06.177850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c536f5d85d75'
down_revision: Union[str, Sequence[str], None] = 'c970ce9dec62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop role-specific columns from child tables
    op.drop_column('instructors', 'department')
    op.drop_column('instructors', 'phone_number')
    op.drop_column('instructors', 'bio')
    op.drop_constraint(op.f('students_student_id_key'), 'students', type_='unique')
    op.drop_column('students', 'department')
    op.drop_column('students', 'phone_number')
    op.drop_column('students', 'student_id')
    op.drop_column('students', 'date_of_birth')
    
    # Add new columns to users table (nullable first)
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('student_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), nullable=False, server_default='en'))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    
    # Migrate data from name to first_name and last_name
    op.execute("""
        UPDATE users 
        SET first_name = COALESCE(split_part(name, ' ', 1), 'User'),
            last_name = COALESCE(NULLIF(TRIM(SUBSTR(name, POSITION(' ' IN name) + 1)), ''), 'Account')
        WHERE first_name IS NULL
    """)
    
    # Make first_name and last_name NOT NULL after migration
    op.alter_column('users', 'first_name', existing_type=sa.String(length=50), nullable=False)
    op.alter_column('users', 'last_name', existing_type=sa.String(length=50), nullable=False)
    
    # Add unique constraint for student_id
    op.create_unique_constraint(None, 'users', ['student_id'])
    
    # Drop the old name column
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'last_password_change')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'institution_id')
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'department')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('students', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('student_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('students_student_id_key'), 'students', ['student_id'], postgresql_nulls_not_distinct=False)
    op.add_column('instructors', sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('instructors', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('instructors', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
