"""revert to proper table structure with role-specific fields

Revision ID: d9c41349c95e
Revises: c536f5d85d75
Create Date: 2026-03-30 07:57:10.239858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c41349c95e'
down_revision: Union[str, Sequence[str], None] = 'c536f5d85d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('instructors', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('instructors', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('instructors', sa.Column('profile_picture_url', sa.String(), nullable=True))
    
    # Add student_id column as nullable first
    op.add_column('students', sa.Column('student_id', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('profile_picture_url', sa.String(), nullable=True))
    
    # Set default values for existing student_id records (using user ID)
    op.execute("""
        UPDATE students 
        SET student_id = 'STU-' || CAST(id AS VARCHAR)
        WHERE student_id IS NULL
    """)
    
    # Now make student_id NOT NULL
    op.alter_column('students', 'student_id', existing_type=sa.String(length=50), nullable=False)
    op.create_unique_constraint(None, 'students', ['student_id'])
    op.drop_constraint(op.f('users_student_id_key'), 'users', type_='unique')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'institution_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'department')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('student_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_student_id_key'), 'users', ['student_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'profile_picture_url')
    op.drop_column('students', 'department')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'phone_number')
    op.drop_column('students', 'student_id')
    op.drop_column('instructors', 'profile_picture_url')
    op.drop_column('instructors', 'department')
    op.drop_column('instructors', 'phone_number')
    op.drop_column('instructors', 'bio')
    # ### end Alembic commands ###
