import { createApi } from "@reduxjs/toolkit/query/react"
import baseQuery from "@/features/baseQuery"

export const api = createApi({
  reducerPath: "api",
  baseQuery: baseQuery,
  tagTypes: [
    "CATEGORIES",
    "COURSES",
    "EBOOKS",
    "USERS",
    "ORDERS",
    "SUPPORT_TICKETS",
    "WISHLIST",
    "MEDIA",
    "INSTRUCTORS",
    "CHAPTERS",
    "LESSONS",
    "QUIZZES",
    "STUDENTS",
    "ENROLLMENTS",
    "REVIEWS",
    "QUIZ_SUBMISSIONS",
    "BATCHES",
    "PROGRAMS",
    "ASSIGNMENTS",
    "CERTIFICATES",
    "PAYMENTS",
    "COUPONS",
    "BADGES",
    "LIVE_CLASSES",
    "SETTINGS",
    "TRACKING",
    "PERMISSIONS",
    "INVITATIONS",
    "EMAIL_ACCOUNTS",
    "EMAIL_TEMPLATES",
    "BATCH_ENROLLMENTS",
    "PAYMENT_GATEWAYS",
    "COURSE_DASHBOARD",
    "LESSON_PROGRESS",
    "DISCUSSIONS",
    "COMMENTS",
    "NOTIFICATIONS",
    "ROLES",
    "ROLE_PROFILES",
    "FEATURE_FLAGS",
    "ME",
    "STATISTICS",
  ],
  endpoints: () => ({}),
})

export default api
